### ISSUE TITLE
Use pylama for code quality assurance (it's great)

### ISSUE THREAD

**Issue by lwm** [OpenIDC/pyoidc#298]
https://github.com/klen/pylama

This in combination with https://github.com/OpenIDC/pyoidc/issues/297 make for nice guarantees on style.

- [x] "*" imports and unused imports #305 
- [x] unused local variable #306
- [x] whitespace errors, blank lines errors #307
- [x] other errors and travis integration #308
- [ ] mccabe score below 15

**Comment by lwm** [comment]
This will certainly require a heroic effort :beers:

**Comment by lwm** [comment]
Closing in favour of https://github.com/OpenIDC/pyoidc/issues/311.
